SELECT 
B.YEAR,
B.MONTH,
A.GENDER,
COUNT(GENDER)
FROM USER_INFO AS A
INNER JOIN (
SELECT DISTINCT
USER_ID,
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH
FROM ONLINE_SALE
) AS B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY MONTH, GENDER
ORDER BY 1,2,3
