SELECT 
DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
PRODUCT_ID,
USER_ID,
SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM (
SELECT 
USER_ID,
PRODUCT_ID,
SALES_AMOUNT,
SALES_DATE
FROM ONLINE_SALE
UNION 
SELECT 
NULL AS USER_ID,
PRODUCT_ID,
SALES_AMOUNT,
SALES_DATE
FROM OFFLINE_SALE
) AS A
WHERE SALES_DATE LIKE '2022-03%'
GROUP BY USER_ID, PRODUCT_ID, SALES_DATE
ORDER BY 1, 2, 3