SELECT 
    YEAR,
    MONTH,
    COUNT(*) AS PUCHASED_USERS,
    ROUND((COUNT(*) / (SELECT COUNT(USER_ID) AS USERS FROM USER_INFO WHERE JOINED LIKE '2021%')),1) AS PUCHASED_RATIO
FROM (
    SELECT 
         YEAR(SALES_DATE) AS YEAR,
         MONTH(SALES_DATE) AS MONTH,
         USER_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, MONTH
    ) AS A
INNER JOIN (
    SELECT 
         USER_ID
    FROM USER_INFO 
    WHERE JOINED LIKE '2021%'
    ) AS B
ON A.USER_ID = B.USER_ID
GROUP BY MONTH
ORDER BY 1, 2