SELECT 
A.MONTH,
A.CAR_ID,
A.RECORDS
FROM (
SELECT 
CAR_ID,
MONTH(START_DATE) AS MONTH,
COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID, MONTH
) AS A
INNER JOIN (
SELECT 
CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(CAR_ID) > 4
) AS B
ON A.CAR_ID = B.CAR_ID
ORDER BY 1, 2 DESC