SELECT 
CONCAT('/home/grep/src/',A.BOARD_ID,'/',A.FILE_ID,A.FILE_NAME,A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS A
LEFT OUTER JOIN (
SELECT *
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
LIMIT 1
) AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE B.BOARD_ID IS NOT NULL
ORDER BY A.FILE_ID DESC
