WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM hours
    WHERE HOUR < 23
)
SELECT hours.HOUR, COALESCE(COUNT(animal.DATETIME), 0) AS COUNT
FROM hours
LEFT JOIN ANIMAL_OUTS AS animal
ON hours.HOUR = HOUR(animal.DATETIME)
GROUP BY hours.HOUR
ORDER BY hours.HOUR;