SELECT 
A.USER_ID,
A.NICKNAME,
CONCAT(A.CITY,' ',A.STREET_ADDRESS1,' ',A.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO,4,4),'-',RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER AS A
INNER JOIN (
SELECT *
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
) AS B
ON A.USER_ID = B.WRITER_ID
ORDER BY 1 DESC