SELECT 
C.FLAVOR
FROM (
SELECT 
B.FLAVOR,
SUM((IFNULL(A.TOTAL_ORDER,0)+IFNULL(B.TOTAL_ORDER,0))) AS TOTAL_ORDER
FROM FIRST_HALF AS A
RIGHT OUTER JOIN JULY AS B
ON A.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY FLAVOR
ORDER BY TOTAL_ORDER DESC
) AS C
LIMIT 3