SELECT 
U.USER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS U
INNER JOIN  (
SELECT 
WRITER_ID,
SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
ORDER BY 2
) AS B
ON U.USER_ID = B.WRITER_ID
WHERE B.TOTAL_SALES >= 700000 