SELECT 
C.MEMBER_NAME,
D.REVIEW_TEXT,
DATE_FORMAT(D.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS C
INNER JOIN (
SELECT
A.MEMBER_ID,
A.REVIEW_TEXT,
A.REVIEW_DATE
FROM REST_REVIEW AS A
INNER JOIN (
SELECT 
MEMBER_ID,
COUNT(MEMBER_ID) AS COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (
    SELECT MAX(COUNT)
    FROM (
        SELECT COUNT(MEMBER_ID) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS SUB
  )
) AS B
ON A.MEMBER_ID = B.MEMBER_ID
) AS D
ON C.MEMBER_ID = D.MEMBER_ID
ORDER BY 3,2