SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN (
SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID
) AS BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY