SELECT 
A.CAR_ID,
CASE 
    WHEN B.CAR_ID IS NULL THEN '대여 가능'
    ELSE '대여중'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN (
SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATEDIFF('2022-10-16',START_DATE) >= 0 AND DATEDIFF(END_DATE,'2022-10-16') >= 0
GROUP BY CAR_ID
) AS B
ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC