SELECT A.ID,A.NAME,A.HOST_ID
FROM PLACES AS A
LEFT OUTER JOIN (
SELECT 
HOST_ID,
COUNT(HOST_ID) AS COUNT
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT > 1
) AS B
ON A.HOST_ID = B.HOST_ID
WHERE B.HOST_ID IS NOT NULL
ORDER BY 1