SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
INNER JOIN (
SELECT * 
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE = '세단'
) AS B
ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE LIKE '2022-10%'
GROUP BY A.CAR_ID
ORDER BY 1 DESC