SELECT 
A.REST_ID,
B.REST_NAME,
B.FOOD_TYPE,
B.FAVORITES,
B.ADDRESS,
ROUND(AVG(A.REVIEW_SCORE),2) AS REVIEW_SCORE
FROM REST_REVIEW AS A
INNER JOIN (
SELECT *
FROM REST_INFO
WHERE ADDRESS LIKE '서울%'
) AS B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
ORDER BY 6 DESC, 4 DESC